### ISSUE TITLE
issue new release

### ISSUE THREAD

**Issue by colemickens** [yeslogic/fontconfig-rs#10]
`wldash` uses this lib and is broken on aarch64 because of this lib: https://github.com/kennylevinsen/wldash/issues/42

It seems you have fixes, but they're not released. Can you tag and push a new release for crates.io users?

Thanks.

**Comment by wezm** [comment]
New release was published 22 Feb. Sorry it took so long. I didn't have notifications enabled on this repo so I didn't see this issue.
