### ISSUE TITLE
License file missing in fontconfig crate

### ISSUE THREAD

**Issue by ghost** [yeslogic/fontconfig-rs#15]
Hi, fedora use the source from crates.io to make package. it seem that the license is not include in the source of crates.io.

Having the file include in the crate source would ease packaging to not have to make a copy from github manually.

**Comment by ghost** [comment]
The same apply for yeslogic-fontconfig-sys.

**Comment by wezm** [comment]
I've made changes in f23345b to address this. Will aim to get a new release out after #16 is merged.

**Comment by wezm** [comment]
#16 needs some follow up so I've published new releases today.
