### ISSUE TITLE
Missing Apache-2.0 license for fontconfig-sys

### ISSUE THREAD

**Issue by kalev** [yeslogic/fontconfig-rs#29]
It looks like [fontconfig-sys/src/lib.rs](https://github.com/yeslogic/fontconfig-rs/blob/master/fontconfig-sys/src/lib.rs) is licensed under Apache-2.0 or MIT but the Cargo.toml file only lists MIT. I guess it should read "Apache-2.0 OR MIT" in Cargo.toml?

Could you also add the Apache license text to fontconfig-sys as the license header talks about it?

This was noticed during the Fedora package review in https://bugzilla.redhat.com/show_bug.cgi?id=2141070

Thanks!

**Comment by wezm** [comment]
Well spotted. I have reviewed the history of how things came to the current state and the intention when including the bindings from the servo project was to accept that code under the MIT license, matching the non-sys crate and the license of the original -sys crate. I will remove the comment as the LICENCE file attributes the servo developers and is the MIT license that code was accepted under.

**Comment by kalev** [comment]
Sounds good to me. Thanks!

**Comment by wezm** [comment]
Ok that's done and I've published `fontconfig-sys` 4.0.1

**Comment by kalev** [comment]
Excellent, thank you!
