### ISSUE TITLE
lib name conflict with servo/rust-fontconfig

### ISSUE THREAD

**Issue by jgarnierGit** [yeslogic/fontconfig-rs#33]
Hi there,

I have recently identified a lib name conflict between this crate and https://github.com/servo/rust-fontconfig,

I opened a thread here https://users.rust-lang.org/t/dependencies-links-resolver-conflict/87801/4
to illustrate a cohabitation incompatibilities between 2 major crates in their domain.

In my opinion, the solution of less effort would be to synchronize with the other lib to rename one or the other and remove the conflict.

What do you think of that solution ?

Resolving this conflict can improve a lot the Rust crates ecosystem, so I have opened a similar issue on the servo/rust-fontconfig repo 
=> https://github.com/servo/rust-fontconfig/issues/44
Open to discussion :)
Kind regards

**Comment by wezm** [comment]
As Manish pointed out in the other issue, I'm not sure this can be fixed since the `links = "fontconfig"` is specifying that the crates links with the native (C) library called `fontconfig`, which can't be changed.

**Comment by jgarnierGit** [comment]
Thanks for your clarification, it's much clearer that I misunderstood what was the links goal.
